### ISSUE TITLE
[group]: refactor "addresses" argument to be singluar

### ISSUE THREAD

**Issue by rymancl** [rymancl/terraform-provider-dotcommonitor#18]
addresses -> address

**Comment by krishnaindani** [comment]
@rymancl Is it about making a change from `Addresses` struct to `Address` and updating it wherever it is used? Am I understanding it correctly? I can work on it if you could provide more info.

**Comment by rymancl** [comment]
> @rymancl Is it about making a change from `Addresses` struct to `Address` and updating it wherever it is used? Am I understanding it correctly? I would like to work on it if you could provide more info.

Hi @krishnaindani!

The struct is fine. This was about renaming the `addresses` argument to `address` in resource_group.go, since it is a block by default and that singular naming makes more sense. The configuration for multiple addresses currently would look like:

```hcl
addresses {
  # arguments here
}

addresses {
  # arguments here
}
```

But I'm second guessing that and considering using `ConfigMode: schema.SchemaConfigModeAttr` instead so it would be a single argument as a list. 

This is related to #17  but I'm still thinking on which way is better. 

Any thoughts?

**Comment by krishnaindani** [comment]
Don't have the best on top of my head looking at this no, will go through a code and might be able to see what might be better.

**Comment by krishnaindani** [comment]
Just to confirm, we are referring to this one https://github.com/rymancl/terraform-provider-dotcommonitor/blob/main/dotcommonitor/resource_group.go#L36, correct?

**Comment by rymancl** [comment]
> Just to confirm, we are referring to this one https://github.com/rymancl/terraform-provider-dotcommonitor/blob/main/dotcommonitor/resource_group.go#L36, correct?

Yes that's correct. 
And if `addresses` is changed to `address`, I'd probably want to change the `address` element (for email) to `email_address` or something.

**Comment by krishnaindani** [comment]
> > Just to confirm, we are referring to this one https://github.com/rymancl/terraform-provider-dotcommonitor/blob/main/dotcommonitor/resource_group.go#L36, correct?
> 
> Yes that's correct.
> And if `addresses` is changed to `address`, I'd probably want to change the `address` element (for email) to `email_address` or something.

gotcha.

**Comment by rymancl** [comment]
@krishnaindani I researched this a bit more and I don't think this change is needed.

If we follow the AWS provider conventions, they keep the argument plural in situations where there can be more than one block, and singular when the block has a MaxItems set to 1.

Example of [aws_launch_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template).

* block_device_mappings & elastic_gpu_specifications can have multiple -> plural
* elastic_inference_accelerator can only have 1 -> singular

Thank you for offering to work on this though, it's much appreciated!

**Comment by krishnaindani** [comment]
> @krishnaindani I researched this a bit more and I don't think this change is needed.
> 
> If we follow the AWS provider conventions, they keep the argument plural in situations where there can be more than one block, and singular when the block has a MaxItems set to 1.
> 
> Example of [aws_launch_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template).
> 
> * block_device_mappings & elastic_gpu_specifications can have multiple -> plural
> * elastic_inference_accelerator can only have 1 -> singular
> 
> Thank you for offering to work on this though, it's much appreciated!

yeah, that makes sense. You're Welcome. Let me know if there is any other work I can pick up.
